### ISSUE TITLE
compute_features_transactions this function is missing cos and sine of month

### ISSUE THREAD

**Issue by mukulsn** [decodingml/hands-on-personalized-recommender#7]
in compute_features_transactions this function in this file 

`from recsys.features.transactions import compute_features_transactions`

i think it is missing to calculate month sine and cosine function.

please review it once.

the function is this as of now:

def compute_features_transactions(df: pl.DataFrame) -> pl.DataFrame:
    """
    Prepare transaction data by performing several data transformations.

    This function does the following:
    1. Converts 'article_id' to string type.
    2. Converts 't_dat' to datetime type.
    3. Extracts year, month, day, and day of week from 't_dat'.
    4. Calculates sine and cosine of the month for cyclical feature encoding.
    5. Converts 't_dat' to epoch milliseconds.

    Parameters:
    - df (pl.DataFrame): Input DataFrame containing transaction data.

    Returns:
    - pl.DataFrame: Processed DataFrame with transformed transaction data.
    """

    return (
        df.with_columns(
            [
                pl.col("article_id").cast(pl.Utf8).alias("article_id"),
            ]
        )
        .with_columns(
            [
                pl.col("t_dat").dt.year().alias("year"),
                pl.col("t_dat").dt.month().alias("month"),
                pl.col("t_dat").dt.day().alias("day"),
                pl.col("t_dat").dt.weekday().alias("day_of_week"),
            ]
        )
        .with_columns([(pl.col("t_dat").cast(pl.Int64) // 1_000_000).alias("t_dat")])
    )

**Comment by iusztinpaul** [comment]
Hello @mukulsn,

Great observation!

The month sine and cosine features are computed on-demand as UDF functions: https://github.com/decodingml/personalized-recommender-course/blob/main/recsys/hopsworks_integration/feature_store.py#L69
